name = "principles-client"
main = "src/worker.ts"
compatibility_date = "2024-12-01"

[vars]
API_URL = "https://principles-api.cogell.workers.dev"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
