name = "principles-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
AUTH_BYPASS = "false"

[[d1_databases]]
binding = "DB"
database_name = "principles"
database_id = "d0b3cf58-e378-44ae-bf1c-a5581775961a"

[[r2_buckets]]
binding = "R2"
bucket_name = "principles-docs"
